baseURL = "https://heng-mei.github.io/"
title = "Heng-Mei Blog"
theme = "FixIt"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
enableRobotsTXT = true
enableEmoji = true

mainSections = ["posts", "algorithms", "notes"]

[outputs]
home = ["html", "rss", "archives", "offline", "readme", "baidu_urls", "search"]
page = ["html", "markdown"]
section = ["html", "rss"]
taxonomy = ["html"]
term = ["html", "rss"]

[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"
collection = "collections"

[params]
capitalizeTitles = false

[params.breadcrumb]
enable = true

[params.cookieconsent]
enable = false

[params.backToTop]
enable = true
scrollpercent = true

[params.home]
[params.home.profile]
enable = true
gravatarEmail = "l888999666y@gmail.com"
avatarURL = "/avatar.jpg"
avatarMenu = "github"
title = "Heng-Mei <img src=\"/face-in-clouds-emoji.gif\"  class=\"emoji\"/>"
subtitle = "横眉冷对千夫指，俯首甘为孺子牛。"
typeit = true
social = true

[params.home.posts]
enable = false

[params.author]
name = "Heng-Mei"
email = "l888999666y@gmail.com"
link = "https://github.com/Heng-Mei"
avatar = "/avatar.jpg"

[params.footer]
enable = true
copyright = true
author = true
since = "2025"
gov = ""
icp = ""
license = "<a href='https://opensource.org/licenses/MIT'>MIT License</a>"
[params.footer.powered]
enable = false

[params.search]
enable = true
type = "fuse"
contentLength = 4000
placeholder = ""
maxResultLength = 10
snippetLength = 30
highlightTag = "em"
absoluteURL = false

[params.search.fuse]
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

[params.social]
GitHub = "Heng-Mei"
RSS = false

[params.recentlyUpdated]
archives = true
section = true
list = true
days = 30
maxCount = 10

[menu]

[[menu.main]]
identifier = "github"
name = " "
url = "https://github.com/Heng-Mei"
weight = 1

[[menu.main]]
name = "随想"
url = "/posts/"
weight = 10

[[menu.main]]
name = "算法"
url = "/algorithms/"
weight = 12

[[menu.main]]
name = "笔记"
url = "/notes/"
weight = 15

[[menu.main]]
name = "归档"
url = "/archives/"
weight = 20

[[menu.main]]
name = "合集"
url = "/collections/"
weight = 21

[[menu.main]]
name = "分类"
url = "/categories/"
weight = 22

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 25

[markup]
[markup.highlight]
codeFences = true
lineNos = false
lineNumbersInTable = true
noClasses = false

[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[params.page.math]
enable = true
type = "mathjax"
# MathJax server-side rendering (https://www.mathjax.org)
# MathJax config: https://docs.mathjax.org/en/latest/options/index.html
[params.page.math.mathjax]
cdn = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
[params.page.math.mathjax.packages]
"[+]" = ["physics", "xypic"]
# custom macros map
# syntax: <macro> = <definition>
[params.page.math.mathjax.macros]
# "bold" = ["{\\bf #1}", 1]   # usage: $\bold{math}$
[params.page.math.mathjax.loader]
load = ["ui/safe", "[tex]/physics", "[custom]/xypic.js"]
[params.page.math.mathjax.loader.paths]
custom = "https://cdn.jsdelivr.net/gh/sonoisa/XyJax-v3@3.0.1/build/"
[params.page.math.mathjax.options]
enableMenu = true
# HTML tags that won't be searched for math
skipHtmlTags = [
  "script",
  "noscript",
  "style",
  "textarea",
  "pre",
  "code",
  "math",
  "select",
  "option",
  "mjx-container",
]
# class that marks tags not to search
ignoreHtmlClass = "mathjax_ignore"
# HTML tags that can appear within math
[params.page.math.mathjax.options.includeHtmlTags]
# "#comment" = ""
# br = "\n"
# wbr = ""

[params.page.math.mathjax.tex]
tags = "all"
processEscapes = true
processEnvironments = true

[params.page.math.mathjax.tex.physics]
italicdiff = false
arrowdel = false

[params.page]
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
linkToMarkdown = false
linkToSource = false
linkToEdit = false
linkToReport = false
linkToVscode = false
pageStyle = "normal"
wordCount = true
readingTime = true
collectionList = true

# 目录配置
[params.page.toc]
auto = false
ordered = true

[params.page.heading.number]
enable = true

[params.page.heading.number.format]
h1 = "{title}"
h2 = "{h2} {title}"
h3 = "{h2}.{h3} {title}"
h4 = "{h2}.{h3}.{h4} {title}"
h5 = "{h2}.{h3}.{h4}.{h5} {title}"
h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"

[params.page.heading.toc.ordered]
enable = true

[params.page.share]
enable = false

# 第三方库配置
[params.page.library]

[params.page.library.css]
# someCSS = "some.css"
# 位于 "assets/"
# 或者
# someCSS = "https://cdn.example.com/some.css"

[params.page.library.js]
# someJavascript = "some.js"
# 位于 "assets/"
# 或者
# someJavascript = "https://cdn.example.com/some.js"


[caches]
[caches.images]
dir = ":cacheDir/images"

[params.verification]
google = "BZknj698kPXN9fxHxb1vFvdc0d-luCM1UYEY0olmDZk"
bing = "5E7A7EA66C53643B33B56812868ABDDA"
